commands/
         __init__.py
         no_op.py
         ace_correct.py
         agc_filter.py
         agc_midpoint.py
         agc_roi.py
         agc_type.py
         baud_rate.py
         brightness.py
         brightness_bias.py
         camera_part.py
         camera_reset.py
         contrast.py
         correction_mask.py
         dde_gain.py
         dde_threshold.py
         digital_output_mode.py
         do_ffc.py
         erase_memory_block.py
         external_sync.py
         ezoom_control.py
         ffc_mode_select.py
         ffc_period.py
         ffc_temp_delta.py
         ffc_warn_time.py
         gain_mode.py
         gain_switch_params.py
         get_nv_memory_size.py
         get_revision.py
         get_spot_meter.py
         get_spot_meter_data.py
         isotherm.py
         isotherm_thresholds.py
         lens_number.py
         lens_response_params.py
         max_agc_gain.py
         memory_status.py
         pan_and_tilt.py
         plateau_level.py
         read_array_average.py
         read_memory.py
         read_sensor.py
         restore_factory_defaults.py
         serial_number.py
         set_defaults.py
         shutter_position.py
         shutter_temp.py
         spatial_threshold.py
         splash_control.py
         spot_display.py
         spot_meter_mode.py
         symbol_control.py
         tail_size.py
         test_pattern.py
         tlin_commands.py
         transfer_frame.py
         video_color_mode.py
         video_mode.py
         video_orientation.py
         video_palette.py
         video_standard.py
         write_nvffc_table.py
